---
title: "3) DataAnalysis"
author: "Carsten Dortans"
date: "22/04/2021"
output: html_document
---

#This document analysis Meridian smart meter data for our research purpose. It exports a clean .csv file

```{r reqlib}

reqLibs <- c("data.table", # data munching
             "drake", # what's done stays done
             "here", # here
             "lubridate", # dates and times
             "ggplot2", # plots
             "skimr", # for skim
             "knitr", # for kable
             "readr", # for .csv
             "hms", # manipulate hms
             "dplyr", # data munching
             "kableExtra", # for tables
             "visNetwork", # for drake's dependency graph
             "callr", # for drake commands
             "readxl",
             "purrr", # for imprting files
             "networkD3", # for more graphic elements
             "ggraph",
             "purrr", # for importing files
             "zoo",
             "tidyr",
             "imputeTS"
)
# load them
woRkflow::loadLibraries(reqLibs)

```


```{r loadData}

CleanDT = data.table::as.data.table(read_csv(file_in("~/greenGridData/externalData//Meridian/2_Cleaned/noSolarMeridianSeasonal.csv"))) #Requires step 2: cleaning data 

CleanDT <- CleanDT[, obsHalfHour:= as_hms(obsHalfHour)] #Converting double() to time 
CleanDT <- CleanDT[, dateTime:=as_datetime(dateTime, tz="Pacific/Auckland")] #No UTC please.....



```

```{r buildingMean}


# Calculate sum of kWh for each day and iD BUT: How to make sure that every day 48 values are considered? Do we need to impute data so that we have 48 obs for each day? What if a day is missing for an iD? 


# SO we want 48 steps for each iD for 28 days of data. Otherwise we wouldn't comapre apples with apples 

sumDT <- copy(CleanDT)

sumDT <- sumDT [, nObs:= .N, keyby =. (iD, SolarPeriod, season )] # Counting the number of observations for each iD and solar period

sumDT <- sumDT[, sumKWH := sum(kWh), keyby =.(iD, SolarPeriod, season)] # calculating total kWh for each iD and solar period over the entire four weeks

sumDT <- sumDT[, portion := sumKWH/nObs] # kWh per observation 


sumDT <- sumDT[, scale := portion*24*28] # scaling the proportion to the exact number of observations four the four week period #24 half hours in the data...

# Once we have different length of hours where solar is NOT generating we have to scale appropriately with ifelse(). For now, as both months have twelve hours of no solar generation we can use the proportion above




sumDT <- sumDT[, .(prepost = scale), keyby =.(iD, SolarPeriod, season)]

sumDT <- unique(sumDT) # getting rid of duplicates


sumDT <- spread(sumDT, SolarPeriod, prepost) # Create a nice data table for plotting where pre solar and post solar are columns 


sumDT <- sumDT[, diffkWh := (`Pre-Solar`-`Post-Solar`)] # Calc the difference in kWh between pre and post solar 


# Remove NA: some households did not have both pre/post data 


sumDT <- sumDT[!is.na(diffkWh)]


sumDT <-sumDT[, diffper := (-diffkWh/`Pre-Solar`)*100] # Calc the per cent change in kWh between pre and post solar


sumDT$season <- factor(sumDT$season, levels = c("Spring", "Summer", "Autumn", "Winter"))



myPlot <- ggplot2::ggplot(sumDT) +
  geom_point(aes(x= `Pre-Solar`,y = diffper )) +
   labs(x="Initial consumption over four weeks in kWh (summer)",y="Change in consumption post solar in %",title="Post solar change (%) outliers=NA, at times with no solar generation")+
   geom_smooth(aes(x= `Pre-Solar`,y = diffper ), method = "lm")+
   geom_hline(aes(yintercept = 0)) +
  #labs(x = "date") +
  #scale_x_continuous( limits = c(0,500))+
   #  geom_vline(aes(xintercept=mean(totalEnergyWh/1000)),
          #  color="blue", linetype="dashed", size=0.5)+
  #
  facet_wrap( ~ season)+
  ylim(-200, 50)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.y = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"))
myPlot



myPlot <- ggplot2::ggplot(sumDT,aes(x= diffper, colour= season)) +
  geom_density() +
   labs(x="Change in consumption post solar in % (summer)",y="density",title="Density of post solar change (summer), at times with no solar generation")+
  #labs(x = "date") +
  #scale_x_continuous( limits = c(0,500))+
   #  geom_vline(aes(xintercept=mean(totalEnergyWh/1000)),
          #  color="blue", linetype="dashed", size=0.5)+
  #facet_wrap( ~ year)+
     xlim(-200, 50)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.y = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"))
myPlot



sum(sumDT$diffper<0)






myPlot <- ggplot2::ggplot(sumDT, aes(x= diffper, colour=season, outlier.shape=NA)) +
  geom_boxplot() +
   labs(x="Change in consumption post solar in % (summer)",y="density",title="Boxplot of post solar change, outliers = NA, at times with no solar generation")+
  #labs(x = "date") +
  #scale_x_continuous( limits = c(0,500))+
   #  geom_vline(aes(xintercept=mean(totalEnergyWh/1000)),
          #  color="blue", linetype="dashed", size=0.5)+
  #facet_wrap( ~ year)+
   xlim(-100, 50)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
      
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.ticks.x = element_line(colour = "black"))
myPlot


```
