---
title: "2) Data Cleaning"
author: "Carsten Dortans"
date: "19/04/2021"
output: html_document
---

#This document analysis Meridian smart meter data for descriprive information. 
```{r reqlib}

reqLibs <- c("data.table", # data munching
             "drake", # what's done stays done
             "here", # here
             "lubridate", # dates and times
             "ggplot2", # plots
             "skimr", # for skim
             "knitr", # for kable
             "readr", # for .csv
             "hms", # manipulate hms
             "dplyr", # data munching
             "kableExtra", # for tables
             "visNetwork", # for drake's dependency graph
             "callr", # for drake commands
             "readxl",
             "purrr", # for imprting files
             "networkD3", # for more graphic elements
             "ggraph",
             "purrr", # for importing files
             "zoo",
             "tidyr",
             "imputeTS",
             "pastecs" #for descritive analyses,
            # "esquisse" #interactive ggplot
)
# load them
woRkflow::loadLibraries(reqLibs)

```

```{r loadData}

dataDT = data.table::as.data.table(read_csv(file_in("~/greenGridData/externalData//Meridian/1_Reshape/finalReshape.csv"))) #Requires step 1: reshaping data from overhead folder

dataDT <- dataDT[, kW:= kWh*2] # We want power instead of energy

```

```{r summary}

summary(dataDT)

```


```{r pastecskWh}

res <- stat.desc(dataDT$kWh)
round(res, 2) #7.4% NA or 0

```

```{r boxplotKWh}

myPlot <- ggplot2::ggplot(dataDT, aes(x= time, y=kW, group=time)) +
  geom_boxplot(outlier.shape=NA) +
   labs(x="Time of day",y="Power (kW)",title="kW distribution over the years and houses")+
   ylim(-2.5,2.5)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"))
  # scale_x_time(breaks = scales::breaks_width("30 min"))

myPlot


```

```{r postSolarBoxplot}

post <- dataDT[!(dataDT$SolarPeriod=="Pre-Solar"),]


myPlot <- ggplot2::ggplot(post, aes(x= time, y=kW, group=time)) +
  geom_boxplot(outlier.shape=NA) +
   labs(x="Time of day",y="Power (kW)",title="kW distribution post solar over the years and houses")+
   ylim(-2.5,2.5)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"))
  # scale_x_time(breaks = scales::breaks_width("30 min"))

myPlot


```

```{r WhyPostValuesZeroAtNight}

#Why post-installation values zero over night?

postC <- copy(post)

postC <- filter(postC, kW < 0, 
                time >= as.hms("23:00:00") & time <= as.hms("24:00:00") |
                time <= as.hms("05:00:00") & time >= as.hms("00:00:00"))

tally(group_by(postC, iD)) # Negative values caused by 12 houses
tally(group_by(postC, date)) # -> many dates are affected # MAny dates are affected


myPlot <- ggplot2::ggplot(postC, aes(x=kW)) +
  geom_histogram(binwidth = 0.5) +
   labs(x="kW",y="nObs",title="Range of negative power values during non solar hours after solar installation")+
 #  scale_fill_discrete(name = "Household iD")+
  # ylim(-2.5,2.5)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"))
  # scale_x_time(breaks = scales::breaks_width("30 min"))

myPlot



```

```{r preSolarBoxplot}

pre <- dataDT[!(dataDT$SolarPeriod=="Post-Solar"),]


myPlot <- ggplot2::ggplot(pre, aes(x= time, y=kW, group=time)) +
  geom_boxplot(outlier.shape=NA) +
   labs(x="Time of day",y="Power (kW)",title="kW distribution pre solar over the years and houses")+
   ylim(-2.5,2.5)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"))
  # scale_x_time(breaks = scales::breaks_width("30 min"))

myPlot

```

```{r WhyPreValuesSmallerZero}

#Why are pre-installation values in the boxplot smaller than zero? Is it just one house?

preC <- copy(pre)

preC <- filter(preC, kW < 0)

# How many houses had negative values pre installation?

tally(group_by(preC, iD)) # -> Negative values caused by five houses 

tally(group_by(preC, date)) # -> many dates are affected 

# What is the range of negative values per household?

myPlot <- ggplot2::ggplot(preC, aes(x=kW, fill = as.factor(iD))) +
  geom_histogram(binwidth = 0.5) +
   labs(x="kW",y="nObs",title="Range of negative power values before solar installation")+
   scale_fill_discrete(name = "Household iD")+
  # ylim(-2.5,2.5)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        axis.ticks.y = element_line(colour = "black"))
  # scale_x_time(breaks = scales::breaks_width("30 min"))

myPlot





```


```{r whereNA}

plotDT <- dataDT[is.na(kW), .(nNA = .N), keyby = .(date, time)] # count the NAs by ID and date

ggplot(plotDT, aes(x = date, y = time, fill = nNA)) +
geom_tile() +
scale_fill_continuous(high = "red", low = "green")+
  geom_tile(width=0.6,height=0.6)

```

```{r howManyIDs}

tally(group_by(dataDT, iD))

```

```{r nObsOverTime}


nObsDT <- dataDT
nObsDT <- nObsDT[, nObs := ifelse(is.na(nObsDT$kW), 0,1 )]
nObsDT <- nObsDT[, sumnObs:=sum(nObs), keyby =.(date)]


myPlot <- ggplot2::ggplot(nObsDT, aes(x= date, y=sumnObs)) +
  geom_line() +
   labs(x="Date",y="nObs",title="nObs that are not NA")+
  # ylim(-2.5,2.5)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.ticks.x = element_line(colour = "black"))
  # scale_x_time(breaks = scales::breaks_width("30 min"))

myPlot




```

````{r measurementError}

# Objective: Look at the dates when post installation kW reaches zero overninght. Is this a battery or measurement error?

postC <- copy(post)

postC <- filter(postC, kW < 0, 
                time >= as.hms("23:00:00") & time <= as.hms("24:00:00") |
                time <= as.hms("05:00:00") & time >= as.hms("00:00:00"))


tally(group_by(postC, iD)) # Negative values caused by 12 houses
tally(group_by(postC, date)) # -> many dates are affected 

select <- filter(postC, iD == "cd_79_int" )
tally(group_by(select, date)) # -> many dates are affected 

select <- filter(post, date == "2019-08-31", iD== "cd_79_int") # the day when it went zero overnight
select2 <- filter(post, date == "2019-08-29", iD== "cd_79_int") # two days prior to this in comparison 

#Plot this 

myPlot <- ggplot2::ggplot(select2, aes(x= time, y=kW)) +
  geom_line() +
   labs(x="Time",y="Power (kW)",title="Battery or measurement error? 2019-08-29, cd_79_int")+
  # ylim(-2.5,2.5)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.ticks.x = element_line(colour = "black"))
  # scale_x_time(breaks = scales::breaks_width("30 min"))

myPlot


````


```{r OERCtalk}

# Objective: How much does consumption from the grid decline after installing PV by house?
# 1: Annual change 

# Challenges: Need to make sure that pre-post has the same number of obs by iD (compare apples with apples)
# What is the best way to visulaise this huge spread?
nObsDT <- copy(dataDT)
nObsDT <- dataDT[, nObsPrePost := .N, keyby =.(iD, SolarPeriod)]
nObsDT <- nObsDT[, sumnObs := .N, keyby =.(iD)]
nObsDT <- nObsDT[, richness := (nObsPrePost/sumnObs)*2] #So ideally we want half of the obs pre and half post. This shows how close each half is recorded


nObsDT <- nObsDT[!iD %in% nObsDT[`richness` <0.75 , iD], ] #Delte iDs if half of the data does not reach 75%
nObsDT <- nObsDT[!iD %in% nObsDT[`richness` > 1.25, iD], ] #Delete iDs if half the data exceeds 125%

#From earlier analysis we know the houses with measurement errors that result in negative values over night.
postC <- copy(post)

postC <- filter(postC, kW < 0, 
                time >= as.hms("23:00:00") & time <= as.hms("24:00:00") |
                time <= as.hms("05:00:00") & time >= as.hms("00:00:00"))


badOnes <- as.data.table(tally(group_by(postC, iD))) # Negative values caused by 12 houses

#Let us take them out now.
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_119" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_120" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_137" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_177" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_181" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_39" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_42" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_5" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_68" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_79_int" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_99" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_69" , iD], ] 
nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_54" , iD], ] 

#Another weird house using more than 48,800kWh per year.

nObsDT <- nObsDT[!iD %in% nObsDT[`iD` == "cd_44" , iD], ] 
# Export this cleaned data 




cleanedMerdidianDT <- data.table::fwrite(nObsDT,  "~/greenGridData/externalData//Meridian/2_Cleaned/cleanedMeridian.csv")

#Export to server


```

```{r extractMeridianLink}

#Any data processing has to be made before this code...
# Extracting linked Meridian houses with interviews


#InterviewDT <- subset(dataDT, iD %like% "int") #Works well


```



