---
title: "3) DataAnalysis"
author: "Carsten Dortans"
date: "22/04/2021"
output: html_document
---

#This document analysis Meridian smart meter data for our research purpose. It exports a clean .csv file

```{r reqlib}

reqLibs <- c("data.table", # data munching
             "drake", # what's done stays done
             "here", # here
             "lubridate", # dates and times
             "ggplot2", # plots
             "skimr", # for skim
             "knitr", # for kable
             "readr", # for .csv
             "hms", # manipulate hms
             "dplyr", # data munching
             "kableExtra", # for tables
             "visNetwork", # for drake's dependency graph
             "callr", # for drake commands
             "readxl",
             "purrr", # for imprting files
             "networkD3", # for more graphic elements
             "ggraph",
             "purrr", # for importing files
             "zoo",
             "tidyr",
             "imputeTS"
)
# load them
woRkflow::loadLibraries(reqLibs)

```


```{r loadData}

CleanDT = data.table::as.data.table(read_csv(file_in("~/greenGridData/externalData//Meridian/2_Cleaned/cleanMeridian.csv"))) #Requires step 2: cleaning data 

CleanDT <- CleanDT[, obsHalfHour:= as_hms(obsHalfHour)] #Converting double() to time 
CleanDT <- CleanDT[, dateTime:=as_datetime(dateTime, tz="Pacific/Auckland")] #No UTC please.....

```

```{r buildingMean}


# Calculate sum of kWh for each day and iD BUT: How to make sure that every day 48 values are considered? Do we need to impute data so that we have 48 obs for each day? What if a day is missing for an iD? 


# SO we want 48 steps for each iD for 28 days of data. Otherwise we wouldn't comapre apples with apples 

sumDT <- copy(CleanDT)

sumDT <- sumDT [, nObs:= .N, keyby =. (iD, SolarPeriod)]

sumDT <- sumDT[, sumKWH := sum(kWh), keyby =.(iD, SolarPeriod)]

sumDT <- sumDT[, portion := sumKWH/nObs]


sumDT <- sumDT[, scale := portion*48*28]


sumDT <- sumDT[, .(prepost = scale), keyby =.(iD, SolarPeriod)]

sumDT <- unique(sumDT)


sumDT <- spread(sumDT, SolarPeriod, prepost)


sumDT <- sumDT[, diffper := (`Post-Solar`/`Pre-Solar`)*(-100)]


# Remove NA: some households did not have both pre/post data 
NAomitDT <- NAomitDT[!is.na(kWh)]

sumDT <- sumDT[!is.na(diffper)]



myPlot <- ggplot2::ggplot(sumDT) +
  geom_point(aes(x= `Pre-Solar`,y = diffper )) +
   labs(x="Initial consumption over four weeks in kWh (summer)",y="Change in consumption post solar in %",title="Initial consumption and post solar change (%)")+
  #labs(x = "date") +
  #scale_x_continuous( limits = c(0,500))+
   #  geom_vline(aes(xintercept=mean(totalEnergyWh/1000)),
          #  color="blue", linetype="dashed", size=0.5)+
  #facet_wrap( ~ year)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.y = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"))
myPlot



myPlot <- ggplot2::ggplot(sumDT) +
  geom_density(aes(x= diffper )) +
   labs(x="Change in consumption post solar in % (summer)",y="density",title="Density of post solar change (summer)")+
  #labs(x = "date") +
  #scale_x_continuous( limits = c(0,500))+
   #  geom_vline(aes(xintercept=mean(totalEnergyWh/1000)),
          #  color="blue", linetype="dashed", size=0.5)+
  #facet_wrap( ~ year)+
  theme(text = element_text(family = "Cambria"),
        axis.text.x = element_text(colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.ticks.y = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"))
myPlot



sum(sumDT$diffper<0)



```
